# Generated by Django 2.2.3 on 2019-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_auto_20190521_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image_request')),
                ('quantity', models.IntegerField(default=0)),
                ('request_id', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=15)),
                ('attribute', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
