# Generated by Django 2.2.3 on 2019-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0094_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_date',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='request',
            name='attribute',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterModelTable(
            name='request',
            table='product_request',
        ),
    ]
