# Generated by Django 2.2.3 on 2019-07-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_auto_20190721_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='time',
            new_name='create_time',
        ),
    ]
