# Generated by Django 2.2.3 on 2019-07-22 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_auto_20190722_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 16, 38, 58, 521210)),
        ),
    ]
