# Generated by Django 2.2.3 on 2019-07-22 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_auto_20190722_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
