# Generated by Django 2.2.3 on 2019-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0098_auto_20190722_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
