# Generated by Django 2.2.3 on 2019-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0099_auto_20190722_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.FileField(blank=True, upload_to='image_request'),
        ),
    ]
