# Generated by Django 2.2.3 on 2019-07-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0100_auto_20190722_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-comments_posts__timestamp', '-comments_post__updated']},
        ),
        migrations.AddField(
            model_name='request',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='image_request', width_field='width_field'),
        ),
    ]
