# Generated by Django 2.2.3 on 2019-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0101_auto_20190725_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='price',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
