# Generated by Django 2.2.2 on 2019-07-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0016_shippingmethod_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='type',
            field=models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping'), ('percentage', 'Percentage based shipping')], max_length=30),
        ),
    ]
