# Generated by Django 2.2.2 on 2019-07-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_checkout_estimate_date_receive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='estimate_date_receive',
        ),
    ]
